CLIENT/CodeAssessMetadata/main/default/objects/Candidate__c/Candidate__c.object-meta.xml
<CustomObject>
    <label>Candidate</label>
    <nameField>
        <label>Candidate Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Candidates</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

CLIENT/CodeAssessMetadata/main/default/objects/Candidate__c/fields/Email__c.field-meta.xml
<CustomField>
    <fullName>Email__c</fullName>
    <description>Candidate email</description>
    <label>Email</label>
    <type>Email</type>
</CustomField>

CLIENT/CodeAssessMetadata/main/default/objects/Candidate__c/fields/PhoneNumber__c.field-meta.xml
<CustomField>
    <fullName>PhoneNumber__c</fullName>
    <description>Candidate Phone Number</description>
    <label>PhoneNumber</label>
    <type>Phone</type>
</CustomField>

CLIENT/CodeAssessMetadata/main/default/objects/CandidateQuestionResult__c/CandidateQuestionResult__c.object-meta.xml
<CustomObject>
    <label>CandidateQuestionResult</label>
    <nameField>
        <displayFormat>Question Result {000000000}</displayFormat>
        <label>Question Result Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>CandidateQuestionResults</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

CLIENT/CodeAssessMetadata/main/default/objects/CandidateQuestionResult__c/fields/CandidateResult__c.field-meta.xml
<CustomField>
    <fullName>CandidateResult__c</fullName>
    <label>CandidateResult</label>
    <referenceTo>CandidateResult__c</referenceTo>
    <relationshipName>QuestionResults</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

CLIENT/CodeAssessMetadata/main/default/objects/CandidateQuestionResult__c/fields/Question__c.field-meta.xml
<CustomField>
    <fullName>Question__c</fullName>
    <label>Question</label>
    <referenceTo>Question__c</referenceTo>
    <relationshipName>QuestionResults</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

CLIENT/CodeAssessMetadata/main/default/objects/CandidateQuestionResult__c/fields/Result__c.field-meta.xml
<CustomField>
    <fullName>Result__c</fullName>
    <label>Result</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Result_Status</valueSetName>
    </valueSet>
</CustomField>

CLIENT/CodeAssessMetadata/main/default/objects/CandidateResult__c/CandidateResult__c.object-meta.xml
<CustomObject>
    <label>Candidate Result</label>
    <nameField>
        <displayFormat>Candidate Result {000000000}</displayFormat>
        <label>Candidate Result Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Candidate Results</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

CLIENT/CodeAssessMetadata/main/default/objects/CandidateResult__c/fields/Candidate__c.field-meta.xml
<CustomField>
    <fullName>Candidate__c</fullName>
    <label>Candidate</label>
    <referenceTo>Candidate__c</referenceTo>
    <relationshipLabel>CandidateResults</relationshipLabel>
    <relationshipName>CandidateResults</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

CLIENT/CodeAssessMetadata/main/default/objects/Question__c/Question__c.object-meta.xml
<CustomObject>
    <label>Question</label>
    <nameField>
        <label>Question Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Questions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

CLIENT/CodeAssessMetadata/main/default/objects/Question__c/fields/QuestionTopic__c.field-meta.xml
<CustomField>
    <fullName>QuestionTopic__c</fullName>
    <label>QuestionTopic</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>QuestionTopics</valueSetName>
    </valueSet>
</CustomField>

CLIENT/CodeAssessMetadata/main/default/globalValueSets/QuestionTopics.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Apex Triggers</fullName>
    </customValue>
    <customValue>
        <fullName>Aura Components</fullName>
    </customValue>
    <customValue>
        <fullName>Events</fullName>
    </customValue>
    <customValue>
        <fullName>LWC</fullName>
    </customValue>
    <customValue>
        <fullName>SOQL</fullName>
    </customValue>
    <customValue>
        <fullName>SOSL</fullName>
    </customValue>
    <masterLabel>QuestionTopics</masterLabel>
</GlobalValueSet>

CLIENT/CodeAssessMetadata/main/default/globalValueSets/Result_Status.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Pass</fullName>
    </customValue>
    <customValue>
        <fullName>Fail</fullName>
    </customValue>
    <customValue>
        <fullName>Compile Fail</fullName>
    </customValue>
    <customValue>
        <fullName>Skip</fullName>
    </customValue>
    <masterLabel>Result Status</masterLabel>
</GlobalValueSet>

CLIENT/CodeAssess/main/default/classes/candidateInformationControllerTest.cls
@isTest
public class candidateInformationControllerTest {
    
    @isTest
    public static void runGetCandidiateInfo() {
        //Setup
        Candidate__c newCandidate = new Candidate__c();
        newCandidate.Name = 'Test';
        newCandidate.Email__c = 'Test@gmail.com';
        newCandidate.PhoneNumber__c = '1231231234';
        insert newCandidate;

        candidateResult__c newCandidateResult = new candidateResult__c();
        newCandidateResult.Candidate__c = newCandidate.id;
        insert newCandidateResult;

        ID resultId = newCandidateResult.id;

        //Run Method
        candidateResult__c testCandidateResult = candidateInformationController.getCandidateInfo(resultId);

        System.assertEquals('Test', testCandidateResult.Candidate__r.Name);
        System.assertEquals('test@gmail.com', testCandidateResult.Candidate__r.Email__c);
        System.assertEquals('1231231234', testCandidateResult.Candidate__r.PhoneNumber__c);
    }

    @isTest
    public static void runGetCandidateSummary() {
        //Setup
        Candidate__c newCandidate = new Candidate__c();
        newCandidate.Name = 'Test';
        insert newCandidate;

        candidateResult__c newCandidateResult = new candidateResult__c();
        newCandidateResult.Candidate__c = newCandidate.id;
        insert newCandidateResult;

        ID resultId = newCandidateResult.id;

        Question__c newQuestion = new Question__c();
        newQuestion.QuestionTopic__c = 'LWC';
        insert newQuestion;

        candidateQuestionResult__c newCandidateQuestionResult = new candidateQuestionResult__c();
        newCandidateQuestionResult.Result__c = 'Pass';
        newCandidateQuestionResult.CandidateResult__c = newCandidateResult.id;
        newCandidateQuestionResult.Question__c = newQuestion.id;
        insert newCandidateQuestionResult;

        //Run Method
        List <CandidateQuestionResult__c> testCandidateQuestionResult = candidateInformationController.getCandidateSummary(resultId);
        System.assertEquals('Pass', testCandidateQuestionResult[0].Result__c);
    }

    @isTest
    public static void runCandidateTestResults() {
        //Setup
        Candidate__c newCandidate = new Candidate__c();
        newCandidate.Name = 'Test';
        insert newCandidate;

        candidateResult__c newCandidateResult = new candidateResult__c();
        newCandidateResult.Candidate__c = newCandidate.id;
        insert newCandidateResult;

        ID resultId = newCandidateResult.id;

        Question__c newQuestion = new Question__c();
        newQuestion.QuestionTopic__c = 'LWC';
        insert newQuestion;

        candidateQuestionResult__c newCandidateQuestionResult = new candidateQuestionResult__c();
        newCandidateQuestionResult.Result__c = 'Pass';
        newCandidateQuestionResult.CandidateResult__c = newCandidateResult.id;
        newCandidateQuestionResult.Question__c = newQuestion.id;
        insert newCandidateQuestionResult;

        //Run Method
        List <CandidateQuestionResult__c> testCandidateQuestionResult = candidateInformationController.getCandidateTestResults(resultId);
        System.assertEquals('Pass', testCandidateQuestionResult[0].Result__c);
        System.assertEquals('LWC', testCandidateQuestionResult[0].Question__r.QuestionTopic__c);
    }
}