CLIENT/CodeAssessMetadata/main/default/objects/Candidate__c/Candidate__c.object-meta.xml
<CustomObject>
    <label>Candidate</label>
    <nameField>
        <label>Candidate Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Candidates</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

CLIENT/CodeAssessMetadata/main/default/objects/Candidate__c/fields/User__c.field-meta.xml
<CustomField>
    <fullName>User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>User</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Candidates</relationshipName>
    <type>Lookup</type>
</CustomField>

CLIENT/CodeAssessMetadata/main/default/objects/CandidateResult__c/CandidateResult__c.object-meta.xml
<CustomObject>
    <label>Candidate Result</label>
    <nameField>
        <displayFormat>Candidate Result {000000000}</displayFormat>
        <label>Candidate Result Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Candidate Results</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

CLIENT/CodeAssessMetadata/main/default/objects/CandidateResult__c/fields/Candidate__c.field-meta.xml
<CustomField>
    <fullName>Candidate__c</fullName>
    <label>Candidate</label>
    <referenceTo>Candidate__c</referenceTo>
    <relationshipLabel>CandidateResults</relationshipLabel>
    <relationshipName>CandidateResults</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

CLIENT/CodeAssessMetadata/main/default/objects/CandidateResult__c/fields/PassPercentage__c.field-meta.xml
<CustomField>
    <fullName>PassPercentage__c</fullName>
    <formula>( QuestionsPassed__c  /  TotalQuestions__c ) * 100</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Pass Percentage</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

CLIENT/CodeAssessMetadata/main/default/objects/CandidateResult__c/fields/StartTime__c.field-meta.xml
<CustomField>
    <fullName>StartTime__c</fullName>
    <label>Start Time</label>
    <type>DateTime</type>
</CustomField>

CLIENT/CodeAssessMetadata/main/default/objects/CandidateResult__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>SessionStatus</valueSetName>
    </valueSet>
</CustomField>

CLIENT/CodeAssessMetadata/main/default/objects/CandidateResult__c/fields/SubmitTime__c.field-meta.xml
<CustomField>
    <fullName>SubmitTime__c</fullName>
    <description>The time these candidate results were submitted by the candidate</description>
    <label>Submit Time</label>
    <type>DateTime</type>
</CustomField>

CLIENT/CodeAssessMetadata/main/default/globalValueSets/SessionStatus.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Active</fullName>
    </customValue>
    <customValue>
        <fullName>Completed</fullName>
    </customValue>
    <customValue>
        <fullName>Abandoned</fullName>
    </customValue>
    <masterLabel>Session Status</masterLabel>
</GlobalValueSet>

CLIENT/CodeAssess/main/default/classes/PastResultsController.cls
public with sharing class PastResultsController {
    @AuraEnabled
    public static List <CandidateResult__c> getCandidateResults() {
        ID currentUserId = UserInfo.getUserId();
        //For testing purposes
        //return [SELECT ID, PassPercentage__c, StartTime__c, SubmitTime__c FROM CandidateResult__c WHERE Status__c = 'Completed' AND Candidate__r.User__r.id = '0056300000BTUqeAAH'];

         return [SELECT ID, PassPercentage__c, StartTime__c, SubmitTime__c FROM CandidateResult__c WHERE Status__c = 'Completed' AND Candidate__r.User__r.id = :currentUserId];
    }
}