CLIENT/CodeAssessMetadata/main/default/objects/CandidateResult__c/CandidateResult__c.object-meta.xml
<CustomObject>
    <label>Candidate Result</label>
    <nameField>
        <displayFormat>Candidate Result {000000000}</displayFormat>
        <label>Candidate Result Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Candidate Results</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

CLIENT/CodeAssessMetadata/main/default/objects/CandidateResult__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Candidate Results</relationshipLabel>
    <relationshipName>Candidate_Results</relationshipName>
    <type>Lookup</type>
</CustomField>

CLIENT/CodeAssessMetadata/main/default/objects/CandidateResult__c/fields/PassPercentage__c.field-meta.xml
<CustomField>
    <fullName>PassPercentage__c</fullName>
    <formula>( QuestionsPassed__c  /  TotalQuestions__c ) * 100</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Pass Percentage</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

CLIENT/CodeAssessMetadata/main/default/objects/CandidateResult__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>SessionStatus</valueSetName>
    </valueSet>
</CustomField>

CLIENT/CodeAssessMetadata/main/default/globalValueSets/SessionStatus.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Active</fullName>
    </customValue>
    <customValue>
        <fullName>Completed</fullName>
    </customValue>
    <customValue>
        <fullName>Abandoned</fullName>
    </customValue>
    <masterLabel>Session Status</masterLabel>
</GlobalValueSet>

CLIENT/CodeAssess/main/default/classes/testLWCController.cls
public with sharing class testLWCController {
    @AuraEnabled
    public static List<String> getStatusOptions(){
        try {
            List<Schema.PicklistEntry> valuesList = CandidateResult__c.Status__c.getDescribe().getPicklistValues();
        
            List<String> returnList = new List<String>();
            for (Schema.PicklistEntry ple : valuesList) {
                returnList.add(ple.getLabel());
            }
        
            return returnList;    
        } catch (Exception e) {
            throw new AuraHandledException(e.getMessage());
        }
    }

    @AuraEnabled
    public static List<CandidateResult__c> searchForRecords(String searchTerm, String passPercentage, String statusSelected){
        try {
            List<String> queryTokens = new List<String>();
            queryTokens.add('SELECT Name FROM CandidateResult__c');

            if (queryTokens[0] != '') {
                searchTerm = String.escapeSingleQuotes(searchTerm);
                queryTokens.add('Contact__c.Name LIKE \'%' + searchTerm + '\'%');
            }
            if (queryTokens[0] != '') {
                passPercentage = String.escapeSingleQuotes(passPercentage);
                queryTokens.add('PassPercentage__c > ' + passPercentage);
            }
            if (queryTokens[0] != '') {
                queryTokens.add('Status__c = ' + statusSelected);
            }
            String buildingQuery = '';
            Integer baseLength = queryTokens[0].length();
            for (Integer index = 0; index < queryTokens.size(); index++) {
                buildingQuery += queryTokens[index];
                if (index + 1 < queryTokens.size()) {
                    if (baseLength == buildingQuery.length()) {
                        buildingQuery += ' WHERE ';
                    } else {
                        buildingQuery += ' AND ';
                    }
                }
            }

            return Database.query(buildingQuery);
        } catch (Exception e) {
            throw new AuraHandledException(e.getMessage());
        }
    }

}