CLIENT/CodeAssessMetadata/main/default/objects/CandidateResult__c/CandidateResult__c.object-meta.xml
<CustomObject>
    <label>Candidate Result</label>
    <nameField>
        <displayFormat>Candidate Result {000000000}</displayFormat>
        <label>Candidate Result Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Candidate Results</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

CLIENT/CodeAssessMetadata/main/default/objects/CandidateResult__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Candidate Results</relationshipLabel>
    <relationshipName>Candidate_Results</relationshipName>
    <type>Lookup</type>
</CustomField>

CLIENT/CodeAssessMetadata/main/default/objects/CandidateResult__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>SessionStatus</valueSetName>
    </valueSet>
</CustomField>

CLIENT/CodeAssessMetadata/main/default/globalValueSets/SessionStatus.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Active</fullName>
    </customValue>
    <customValue>
        <fullName>Completed</fullName>
    </customValue>
    <customValue>
        <fullName>Abandoned</fullName>
    </customValue>
    <masterLabel>Session Status</masterLabel>
</GlobalValueSet>

CLIENT/CodeAssess/main/default/classes/PastResultsControllerTest.cls
@IsTest
public without sharing class PastResultsControllerTest {

    @TestSetup
    static void setUpTestData(){
        User candidate =  TESTutilCommunityUser.makeCustomerAndUser('mockTestUser1');
    }

    @IsTest
    public static void TP_GetAllCompletedCandidateResults(){
        Test.startTest();
        // Restrict to only our mock user from TestSetup
        User cUser = [
            SELECT ContactID, Name FROM USER 
            WHERE Profile.Name = 'CodeAssessCandidate' AND Name = 'mockTestUser1'
            LIMIT 1
        ]; 
        Contact c = [SELECT ID FROM Contact WHERE ID =: cUser.ContactId];

        // Make Completed candidate reuslts to view
        CandidateResult__c mockResult1 = new CandidateResult__c();
        mockResult1.Status__c = 'Completed';
        mockResult1.Contact__c = c.id;
        CandidateResult__c mockResult2 = new CandidateResult__c();
        mockResult2.Status__c = 'Completed';
        mockResult2.Contact__c = c.id;
        Insert new CandidateResult__c[]{mockResult1, mockResult2};

        System.runAs(cUser) {
            List<CandidateResult__c> results = PastResultsController.getCandidateResults();
            System.assertEquals(2, results.size());
        }
        Test.stopTest();
    }

}