CLIENT/CodeAssessMetadata/main/default/objects/CandidateResult__c/CandidateResult__c.object-meta.xml
<CustomObject>
    <label>Candidate Result</label>
    <nameField>
        <displayFormat>Candidate Result {000000000}</displayFormat>
        <label>Candidate Result Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Candidate Results</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

CLIENT/CodeAssessMetadata/main/default/objects/CandidateResult__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Candidate Results</relationshipLabel>
    <relationshipName>Candidate_Results</relationshipName>
    <type>Lookup</type>
</CustomField>

CLIENT/CodeAssessMetadata/main/default/objects/CandidateResult__c/fields/PassPercentage__c.field-meta.xml
<CustomField>
    <fullName>PassPercentage__c</fullName>
    <formula>( QuestionsPassed__c  /  TotalQuestions__c ) * 100</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Pass Percentage</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

CLIENT/CodeAssess/main/default/classes/PassPercentageController.cls
public class PassPercentageController {
   
    @AuraEnabled
    public static List<CandidateResult__c> findByPassPercentage(Decimal searchPassPercent) {
        //Filter searches by PASS/FAIL or Candidate Name and order by created date ASC order
        Decimal percent =  searchPassPercent;
    return [SELECT Contact__r.Name, PassPercentage__c FROM CandidateResult__c WHERE PassPercentage__c >= 80];
}
}