CLIENT/CodeAssessMetadata/main/default/objects/CandidateMethodResult__c/CandidateMethodResult__c.object-meta.xml
<CustomObject>
    <description>The results of individual test method runs on a candidate&apos;s question result</description>
    <label>Candidate Method Result</label>
    <nameField>
        <displayFormat>Method Result {000000000}</displayFormat>
        <label>Candidate Method Result Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Candidate Method Results</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

CLIENT/CodeAssessMetadata/main/default/objects/CandidateMethodResult__c/fields/CandidateQuestionResult__c.field-meta.xml
<CustomField>
    <fullName>CandidateQuestionResult__c</fullName>
    <label>Candidate Question Result</label>
    <referenceTo>CandidateQuestionResult__c</referenceTo>
    <relationshipLabel>Candidate Method Results</relationshipLabel>
    <relationshipName>Candidate_Method_Results</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

CLIENT/CodeAssessMetadata/main/default/objects/CandidateQuestionResult__c/CandidateQuestionResult__c.object-meta.xml
<CustomObject>
    <label>CandidateQuestionResult</label>
    <nameField>
        <displayFormat>Question Result {000000000}</displayFormat>
        <label>Question Result Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>CandidateQuestionResults</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

CLIENT/CodeAssessMetadata/main/default/objects/CandidateQuestionResult__c/fields/CandidateResult__c.field-meta.xml
<CustomField>
    <fullName>CandidateResult__c</fullName>
    <label>CandidateResult</label>
    <referenceTo>CandidateResult__c</referenceTo>
    <relationshipName>QuestionResults</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

CLIENT/CodeAssessMetadata/main/default/objects/CandidateQuestionResult__c/fields/Question__c.field-meta.xml
<CustomField>
    <fullName>Question__c</fullName>
    <label>Question</label>
    <referenceTo>Question__c</referenceTo>
    <relationshipName>QuestionResults</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

CLIENT/CodeAssessMetadata/main/default/objects/CandidateResult__c/CandidateResult__c.object-meta.xml
<CustomObject>
    <label>Candidate Result</label>
    <nameField>
        <displayFormat>Candidate Result {000000000}</displayFormat>
        <label>Candidate Result Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Candidate Results</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

CLIENT/CodeAssessMetadata/main/default/objects/CandidateResult__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Candidate Results</relationshipLabel>
    <relationshipName>Candidate_Results</relationshipName>
    <type>Lookup</type>
</CustomField>

CLIENT/CodeAssessMetadata/main/default/objects/CandidateResult__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>SessionStatus</valueSetName>
    </valueSet>
</CustomField>

CLIENT/CodeAssessMetadata/main/default/objects/Question__c/Question__c.object-meta.xml
<CustomObject>
    <label>Question</label>
    <nameField>
        <label>Question Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Questions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

CLIENT/CodeAssessMetadata/main/default/objects/Question__c/fields/PlaceHolder__c.field-meta.xml
<CustomField>
    <fullName>PlaceHolder__c</fullName>
    <label>PlaceHolder</label>
    <length>10000</length>
    <type>LongTextArea</type>
</CustomField>

CLIENT/CodeAssessMetadata/main/default/objects/Question__c/fields/Prompt__c.field-meta.xml
<CustomField>
    <fullName>Prompt__c</fullName>
    <label>Prompt</label>
    <length>10000</length>
    <type>LongTextArea</type>
</CustomField>

CLIENT/CodeAssessMetadata/main/default/objects/Question__c/fields/QuestionTopic__c.field-meta.xml
<CustomField>
    <fullName>QuestionTopic__c</fullName>
    <label>QuestionTopic</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>QuestionTopics</valueSetName>
    </valueSet>
</CustomField>

CLIENT/CodeAssessMetadata/main/default/objects/Question__c/fields/TestClassText__c.field-meta.xml
<CustomField>
    <fullName>TestClassText__c</fullName>
    <label>TestClassText</label>
    <length>100000</length>
    <type>LongTextArea</type>
</CustomField>

CLIENT/CodeAssessMetadata/main/default/objects/QuestionSet__c/QuestionSet__c.object-meta.xml
<CustomObject>
    <label>QuestionSet</label>
    <nameField>
        <label>QuestionSet Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>QuestionSets</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

CLIENT/CodeAssessMetadata/main/default/objects/QuestionSetEntry__c/QuestionSetEntry__c.object-meta.xml
<CustomObject>
    <label>QuestionSetEntry</label>
    <nameField>
        <label>QuestionSetEntry Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>QuestionSetEntries</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

CLIENT/CodeAssessMetadata/main/default/objects/QuestionSetEntry__c/fields/Question__c.field-meta.xml
<CustomField>
    <fullName>Question__c</fullName>
    <label>Question</label>
    <referenceTo>Question__c</referenceTo>
    <relationshipLabel>QuestionSetEntries</relationshipLabel>
    <relationshipName>QuestionSetEntries</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

CLIENT/CodeAssessMetadata/main/default/objects/QuestionSetEntry__c/fields/QuestionSet__c.field-meta.xml
<CustomField>
    <fullName>QuestionSet__c</fullName>
    <label>QuestionSet</label>
    <referenceTo>QuestionSet__c</referenceTo>
    <relationshipLabel>QuestionSetEntries</relationshipLabel>
    <relationshipName>QuestionSetEntries</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

CLIENT/CodeAssessMetadata/main/default/globalValueSets/QuestionTopics.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Apex Triggers</fullName>
    </customValue>
    <customValue>
        <fullName>Aura Components</fullName>
    </customValue>
    <customValue>
        <fullName>Events</fullName>
    </customValue>
    <customValue>
        <fullName>LWC</fullName>
    </customValue>
    <customValue>
        <fullName>SOQL</fullName>
    </customValue>
    <customValue>
        <fullName>SOSL</fullName>
    </customValue>
    <masterLabel>QuestionTopics</masterLabel>
</GlobalValueSet>

CLIENT/CodeAssessMetadata/main/default/globalValueSets/SessionStatus.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Active</fullName>
    </customValue>
    <customValue>
        <fullName>Completed</fullName>
    </customValue>
    <customValue>
        <fullName>Abandoned</fullName>
    </customValue>
    <masterLabel>Session Status</masterLabel>
</GlobalValueSet>

CLIENT/CodeAssess/main/default/classes/testLWCControllerTest.cls
@isTest
public class testLWCControllerTest {
    @TestSetup
    static void makeData(){
        User c = TESTutilCommunityUser.makeCustomerAndUser('mockTestUser1');
    }

    @isTest
    public static void TP_getsStatusPicklistVals (){
        Test.startTest();
        List<String> returnedVals = testLWCController.getStatusOptions(); 
        List<Schema.PicklistEntry> actualList = CandidateResult__c.Status__c.getDescribe().getPicklistValues();

        Boolean missingEntry = false;
        for (Schema.PicklistEntry ple : actualList) {
            if (!returnedVals.contains(ple.getLabel())) {
                missingEntry = true;    
            }
        }
        System.assertEquals(false, missingEntry);
        Test.stopTest();
    }
    @isTest
    public static void TP_searchReturnsExpected (){
        Test.startTest();
        User c = [
            SELECT ContactID, Name FROM USER 
            WHERE Profile.Name = 'CodeAssessCandidate' AND Name = 'mockTestUser1'
            LIMIT 1
        ];
        
        // Question Set for candidate response
        QuestionSet__c mock = new QuestionSet__c(name = 'TestSet');
        insert mock;
        Question__c[] questions = new List<Question__c>();
        for (Integer i = 0; i < 2; i++) {
            Question__c q = new Question__c();
            q.PlaceHolder__c = 'placeholder';
            q.Prompt__c = 'prompt';
            q.QuestionTopic__c = 'SOQL';
            q.TestClassText__c = 'Some test class';
            questions.add(q);
        }
        Insert questions;
        for (Question__c q : questions) {
            QuestionSetEntry__c entry = new QuestionSetEntry__c();
            entry.Question__c = q.id;
            entry.QuestionSet__c = mock.id;
            Insert entry;
        }

        // Build response body in JSON
        String q1m1 = '{"name":"q1m1","outcome":"PASS"}';
        String q1m2 = '{"name":"q1m2","outcome":"PASS"}';
        String q2m1 = '{"name":"q2m1","outcome":"FAIL"}';
        String q2m2 = '{"name":"q2m2","outcome":"PASS"}';
        String q1 = '{"url":"'+questions[0].id+'","startTime":"2020-01-11 05:00:00","endTime":"2020-01-11 05:30:00","methods":['+q1m1+','+q1m2+']}';
        String q2 = '{"url":"'+questions[1].id+'","startTime":"2020-01-11 05:30:00","endTime":"2020-01-11 06:00:00","methods":['+q2m1+','+q2m2+']}';
        String sub = '{"url":"'+mock.id+'","startTime":"2020-01-11 05:00:00","endTime":"2020-01-11 06:00:00","questions":['+q1+','+q2+']}';

        // Make response body:
        String body = sub;
        
        System.runAs(c) {
            // Create POST request
            RestRequest request = new RestRequest();
            request.requestUri = getRESTurl() + 'questionset/';
            request.httpMethod = 'POST';
            request.headers.put('Content-Type', 'application/json');
            request.requestBody = Blob.valueOf(body);
            RestContext.request = request;

            // Ensure successful post
            String response = RESTquestionset.submitTest();
            String expectedValue = 'SUCCESS';
            System.assertEquals(expectedValue, response);
        }

        //Check that result records uploaded to db
        CandidateResult__c[] cResults = [SELECT id FROM CandidateResult__c WHERE Contact__c = :c.ContactId];
        System.assertEquals(1, cResults.size());
        cResults[0].Status__c = 'Active';
        Update cResults[0]; // Set to ACTIVE
        CandidateQuestionResult__c[] cQuestions = [SELECT id FROM CandidateQuestionResult__c WHERE CandidateResult__c = :cResults[0].id];
        System.assertEquals(2, cQuestions.size());
        Set<ID> qResultIDs = new Set<ID>();
        for (CandidateQuestionResult__c q : cQuestions) {
            qResultIDs.add(q.id);
        }
        CandidateMethodResult__c[] cMethods = [SELECT id FROM CandidateMethodResult__c WHERE CandidateQuestionResult__c IN :qResultIDs];
        System.assertEquals(4, cMethods.size());
        Test.stopTest();

        List<CandidateResult__c> returned = testLWCController.searchForRecords('mock', '0', 'Active');
        System.assertEquals(1, returned.size(), returned);
        
    }

    // HELPER TO GET ENDPOINT URL
    private static String getRESTurl() {
        //Network net = [SELECT Name, UrlPathPrefix FROM Network WHERE Name = 'Code Assess Experience'];
        return URL.getSalesforceBaseUrl().toExternalForm() + 'main/services/apexrest/';
    }
}