CLIENT/CodeAssessMetadata/main/default/objects/CandidateMethodResult__c/CandidateMethodResult__c.object-meta.xml
<CustomObject>
    <description>The results of individual test method runs on a candidate&apos;s question result</description>
    <label>Candidate Method Result</label>
    <nameField>
        <displayFormat>Method Result {000000000}</displayFormat>
        <label>Candidate Method Result Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Candidate Method Results</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

CLIENT/CodeAssessMetadata/main/default/objects/CandidateMethodResult__c/fields/CandidateQuestionResult__c.field-meta.xml
<CustomField>
    <fullName>CandidateQuestionResult__c</fullName>
    <label>Candidate Question Result</label>
    <referenceTo>CandidateQuestionResult__c</referenceTo>
    <relationshipLabel>Candidate Method Results</relationshipLabel>
    <relationshipName>Candidate_Method_Results</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

CLIENT/CodeAssessMetadata/main/default/objects/CandidateQuestionResult__c/CandidateQuestionResult__c.object-meta.xml
<CustomObject>
    <label>CandidateQuestionResult</label>
    <nameField>
        <displayFormat>Question Result {000000000}</displayFormat>
        <label>Question Result Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>CandidateQuestionResults</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

CLIENT/CodeAssessMetadata/main/default/objects/CandidateQuestionResult__c/fields/MethodsPassed__c.field-meta.xml
<CustomField>
    <fullName>MethodsPassed__c</fullName>
    <label>Methods Passed</label>
    <summaryFilterItems>
        <field>CandidateMethodResult__c.Outcome__c</field>
        <operation>equals</operation>
        <value>Pass</value>
    </summaryFilterItems>
    <summaryForeignKey>CandidateMethodResult__c.CandidateQuestionResult__c</summaryForeignKey>
    <summaryOperation>count</summaryOperation>
    <type>Summary</type>
</CustomField>

CLIENT/CodeAssessMetadata/main/default/objects/CandidateQuestionResult__c/fields/Result__c.field-meta.xml
<CustomField>
    <fullName>Result__c</fullName>
    <label>Result</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Result_Status</valueSetName>
    </valueSet>
</CustomField>

CLIENT/CodeAssessMetadata/main/default/objects/CandidateQuestionResult__c/fields/TotalMethods__c.field-meta.xml
<CustomField>
    <fullName>TotalMethods__c</fullName>
    <label>Total Methods</label>
    <summaryForeignKey>CandidateMethodResult__c.CandidateQuestionResult__c</summaryForeignKey>
    <summaryOperation>count</summaryOperation>
    <type>Summary</type>
</CustomField>

CLIENT/CodeAssessMetadata/main/default/globalValueSets/Result_Status.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Pass</fullName>
    </customValue>
    <customValue>
        <fullName>Fail</fullName>
    </customValue>
    <customValue>
        <fullName>Compile Fail</fullName>
    </customValue>
    <customValue>
        <fullName>Skip</fullName>
    </customValue>
    <masterLabel>Result Status</masterLabel>
</GlobalValueSet>

CLIENT/CodeAssess/main/default/classes/candidateMethodResultTriggerHelper.cls
public without sharing class candidateMethodResultTriggerHelper {
    public static void onAfterUpdate(List<CandidateMethodResult__c> cmrList) {
        Set<Id> cqrIdSet = new Set<Id>();
        for (CandidateMethodResult__c cmr : cmrList) {
            cqrIdSet.add(cmr.CandidateQuestionResult__c);
        }

        List<CandidateQuestionResult__c> cqrList = [SELECT MethodsPassed__c, TotalMethods__c, Result__c FROM CandidateQuestionResult__c WHERE Id IN :cqrIdSet];

        for (CandidateQuestionResult__c cqr : cqrList) {
            if (cqr.TotalMethods__c == cqr.MethodsPassed__c) {
                cqr.Result__c = 'Pass';
            } else {
                cqr.Result__c = 'Fail';
            }
        }

        UPDATE cqrList;
    }
    public static void onAfterInsert(List<CandidateMethodResult__c> cmrList) {
        onAfterUpdate(cmrList);
    }
}