CLIENT/CodeAssessMetadata/main/default/objects/Question__c/Question__c.object-meta.xml
<CustomObject>
    <label>Question</label>
    <nameField>
        <label>Question Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Questions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

CLIENT/CodeAssessMetadata/main/default/objects/Question__c/fields/PlaceHolder__c.field-meta.xml
<CustomField>
    <fullName>PlaceHolder__c</fullName>
    <label>PlaceHolder</label>
    <length>10000</length>
    <type>LongTextArea</type>
</CustomField>

CLIENT/CodeAssessMetadata/main/default/objects/Question__c/fields/Prompt__c.field-meta.xml
<CustomField>
    <fullName>Prompt__c</fullName>
    <label>Prompt</label>
    <length>10000</length>
    <type>LongTextArea</type>
</CustomField>

CLIENT/CodeAssessMetadata/main/default/objects/Question__c/fields/QuestionTopic__c.field-meta.xml
<CustomField>
    <fullName>QuestionTopic__c</fullName>
    <label>QuestionTopic</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>QuestionTopics</valueSetName>
    </valueSet>
</CustomField>

CLIENT/CodeAssessMetadata/main/default/objects/Question__c/fields/TestClassText__c.field-meta.xml
<CustomField>
    <fullName>TestClassText__c</fullName>
    <label>TestClassText</label>
    <length>100000</length>
    <type>LongTextArea</type>
</CustomField>

CLIENT/CodeAssessMetadata/main/default/objects/QuestionSet__c/QuestionSet__c.object-meta.xml
<CustomObject>
    <label>QuestionSet</label>
    <nameField>
        <label>QuestionSet Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>QuestionSets</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

CLIENT/CodeAssessMetadata/main/default/objects/QuestionSetEntry__c/QuestionSetEntry__c.object-meta.xml
<CustomObject>
    <label>QuestionSetEntry</label>
    <nameField>
        <label>QuestionSetEntry Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>QuestionSetEntries</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

CLIENT/CodeAssessMetadata/main/default/objects/QuestionSetEntry__c/fields/Question__c.field-meta.xml
<CustomField>
    <fullName>Question__c</fullName>
    <label>Question</label>
    <referenceTo>Question__c</referenceTo>
    <relationshipLabel>QuestionSetEntries</relationshipLabel>
    <relationshipName>QuestionSetEntries</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

CLIENT/CodeAssessMetadata/main/default/objects/QuestionSetEntry__c/fields/QuestionSet__c.field-meta.xml
<CustomField>
    <fullName>QuestionSet__c</fullName>
    <label>QuestionSet</label>
    <referenceTo>QuestionSet__c</referenceTo>
    <relationshipLabel>QuestionSetEntries</relationshipLabel>
    <relationshipName>QuestionSetEntries</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

CLIENT/CodeAssessMetadata/main/default/globalValueSets/QuestionTopics.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Apex Triggers</fullName>
    </customValue>
    <customValue>
        <fullName>Aura Components</fullName>
    </customValue>
    <customValue>
        <fullName>Events</fullName>
    </customValue>
    <customValue>
        <fullName>LWC</fullName>
    </customValue>
    <customValue>
        <fullName>SOQL</fullName>
    </customValue>
    <customValue>
        <fullName>SOSL</fullName>
    </customValue>
    <masterLabel>QuestionTopics</masterLabel>
</GlobalValueSet>

CLIENT/CodeAssess/rest/default/classes/RESTQuestionSetTest.cls
@IsTest
public class RESTQuestionSetTest {

    @IsTest
    public static void testGetFullQuestionSetInvalidId() {
        Test.startTest();
        String actualValue = RESTquestionset.getFullQuestionSet('invalidId');
        String expectedValue = 'Invalid query';
        Test.stopTest();

        System.assertEquals(expectedValue, actualValue, actualValue);
    }

    @IsTest
    public static void testGetFullQuestionSetNoQuestions() {
        Test.startTest();
        QuestionSet__c mock = new QuestionSet__c(name = 'TestSet');
        insert mock;
    
        String actualValue = RESTquestionset.getFullQuestionSet(mock.id);
        String expectedValue = 'No questions to query';
        Test.stopTest();

        System.assertEquals(expectedValue, actualValue, actualValue);
    }

    @IsTest
    public static void testGetFullQuestionSetGetQuestions() {
        Test.startTest();
        QuestionSet__c mock = new QuestionSet__c(name = 'TestSet');
        insert mock;

        Question__c[] questions = new List<Question__c>();
        for (Integer i = 0; i < 2; i++) {
            Question__c q = new Question__c();
            q.PlaceHolder__c = 'placeholder';
            q.Prompt__c = 'prompt';
            q.QuestionTopic__c = 'SOQL';
            q.TestClassText__c = 'Some test class';
            questions.add(q);
        }
        Insert questions;
        for (Question__c q : questions) {
            QuestionSetEntry__c entry = new QuestionSetEntry__c();
            entry.Question__c = q.id;
            entry.QuestionSet__c = mock.id;
            Insert entry;
        }
    
        String actualValue = RESTquestionset.getFullQuestionSet(mock.id);
        String expectedValue = '{\"url\":\"' + mock.id + '\",\"questions\":'
        +'[{\"topic\":\"SOQL\",\"testFile\":\"Some test class\",\"prompt\":\"prompt\",\"placeholder\":\"placeholder\",\"identifier\":\"' + questions[0].id + '\"},'
        +'{\"topic\":\"SOQL\",\"testFile\":\"Some test class\",\"prompt\":\"prompt\",\"placeholder\":\"placeholder\",\"identifier\":\"' + questions[1].id + '\"}],'
        +'\"name\":\"TestSet\"}';
        
        Test.stopTest();
        System.assertEquals(expectedValue, actualValue, actualValue);
    }

    @IsTest
    public static void TestMakeQuestionSetList() {
        Test.startTest();
        delete [SELECT ID FROM QuestionSet__c];
        QuestionSet__c mock1 = new QuestionSet__c(name = 'TestSet1');
        insert mock1;
        QuestionSet__c mock2 = new QuestionSet__c(name = 'TestSet2');
        insert mock2;

        String actualValue = RESTquestionset.makeQuestionSetList();
        Boolean match = false;

        if (actualValue == '{\"entries\":[{\"url\":\"' + mock1.id + '\",\"questions\":[],\"name\":\"' + mock1.name + '\"},{\"url\":\"' + mock2.id + '\",\"questions\":[],\"name\":\"' + mock2.name + '\"}]}') {
            match = true;
        }
        if (actualValue == '{\"entries\":[{\"url\":\"' + mock2.id + '\",\"questions\":[],\"name\":\"' + mock2.name + '\"},{\"url\":\"' + mock1.id + '\",\"questions\":[],\"name\":\"' + mock1.name + '\"}]}') {
            match = true;
        }
        
        System.assert(match);
        Test.stopTest();
    }
    @isTest
    static void TP_getQuestionSetList(){
        Test.startTest();
        QuestionSet__c mock1 = new QuestionSet__c(name = 'TestSet1');
        insert mock1;
        QuestionSet__c mock2 = new QuestionSet__c(name = 'TestSet2');
        insert mock2;

        QuestionSet__c[] allTests = [SELECT id, name FROM QuestionSet__c];
        System.assert(allTests.size() > 0);

        // Create GET request
        RestRequest request = new RestRequest();
        request.requestUri = getRESTurl() + 'questionset/'; // no param returns list of questionsets
        request.httpMethod = 'GET';
        RestContext.request = request;

        // Same basic test structure as when testing helper method
        String response = RESTquestionset.getList();
        
        Boolean match = false;
        if (response == '{\"entries\":[{\"url\":\"' + mock1.id + '\",\"questions\":[],\"name\":\"' + mock1.name + '\"},{\"url\":\"' + mock2.id + '\",\"questions\":[],\"name\":\"' + mock2.name + '\"}]}') {
            match = true;
        }
        if (response == '{\"entries\":[{\"url\":\"' + mock2.id + '\",\"questions\":[],\"name\":\"' + mock2.name + '\"},{\"url\":\"' + mock1.id + '\",\"questions\":[],\"name\":\"' + mock1.name + '\"}]}') {
            match = true;
        }
        
        System.assert(match);
        
        Test.stopTest();
    }

    // HELPER TO GET ENDPOINT URL
    private static String getRESTurl() {
        //Network net = [SELECT Name, UrlPathPrefix FROM Network WHERE Name = 'Code Assess Experience'];
        return URL.getSalesforceBaseUrl().toExternalForm() + 'main/services/apexrest/';
    }
}