CLIENT/CodeAssessMetadata/main/default/objects/Question__c/Question__c.object-meta.xml
<CustomObject>
    <label>Question</label>
    <nameField>
        <label>Question Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Questions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

CLIENT/CodeAssessMetadata/main/default/objects/Question__c/fields/Prompt__c.field-meta.xml
<CustomField>
    <fullName>Prompt__c</fullName>
    <label>Prompt</label>
    <length>10000</length>
    <type>LongTextArea</type>
</CustomField>

CLIENT/CodeAssessMetadata/main/default/objects/Question__c/fields/QuestionTopic__c.field-meta.xml
<CustomField>
    <fullName>QuestionTopic__c</fullName>
    <label>QuestionTopic</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>QuestionTopics</valueSetName>
    </valueSet>
</CustomField>

CLIENT/CodeAssessMetadata/main/default/objects/QuestionSet__c/QuestionSet__c.object-meta.xml
<CustomObject>
    <label>QuestionSet</label>
    <nameField>
        <label>QuestionSet Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>QuestionSets</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

CLIENT/CodeAssessMetadata/main/default/objects/QuestionSetEntry__c/QuestionSetEntry__c.object-meta.xml
<CustomObject>
    <label>QuestionSetEntry</label>
    <nameField>
        <label>QuestionSetEntry Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>QuestionSetEntries</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

CLIENT/CodeAssessMetadata/main/default/objects/QuestionSetEntry__c/fields/Question__c.field-meta.xml
<CustomField>
    <fullName>Question__c</fullName>
    <label>Question</label>
    <referenceTo>Question__c</referenceTo>
    <relationshipLabel>QuestionSetEntries</relationshipLabel>
    <relationshipName>QuestionSetEntries</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

CLIENT/CodeAssessMetadata/main/default/objects/QuestionSetEntry__c/fields/QuestionSet__c.field-meta.xml
<CustomField>
    <fullName>QuestionSet__c</fullName>
    <label>QuestionSet</label>
    <referenceTo>QuestionSet__c</referenceTo>
    <relationshipLabel>QuestionSetEntries</relationshipLabel>
    <relationshipName>QuestionSetEntries</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

CLIENT/CodeAssessMetadata/main/default/globalValueSets/QuestionTopics.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Apex Triggers</fullName>
    </customValue>
    <customValue>
        <fullName>Aura Components</fullName>
    </customValue>
    <customValue>
        <fullName>Events</fullName>
    </customValue>
    <customValue>
        <fullName>LWC</fullName>
    </customValue>
    <customValue>
        <fullName>SOQL</fullName>
    </customValue>
    <customValue>
        <fullName>SOSL</fullName>
    </customValue>
    <masterLabel>QuestionTopics</masterLabel>
</GlobalValueSet>

CLIENT/CodeAssess/main/default/classes/questionSetCreatorController.cls
public with sharing class questionSetCreatorController {
    @AuraEnabled
    public static List<Question__c> fetchQuestionList(String searchTerm){
            if (searchTerm != '') {
                searchTerm = String.escapeSingleQuotes(searchTerm);
                return Database.query('SELECT Name, QuestionTopic__c, Prompt__c FROM Question__c WHERE Name LIKE \'%' + searchTerm + '%\'');
            } else {
                return [SELECT Name, QuestionTopic__c, Prompt__c FROM Question__c];
            }
    }

    @AuraEnabled
    public static Boolean checkDuplicate(String qsName){
            List<QuestionSet__c> qList = [SELECT Name FROM QuestionSet__c];
            Set<String> nameSet = new Set<String>();
            for (QuestionSet__c questionSet : qList) {
                nameSet.add(questionSet.Name);
            }
            Integer prevSize = nameSet.size();
            nameSet.add(qsName);
            if (nameSet.size() == prevSize) {
                return true;
            } else {
                return false;
            }
    }

    @AuraEnabled
    public static Boolean insertQuestionSet(String sName, List<String> nameList){
            try {
                QuestionSet__c qs = [SELECT Id FROM QuestionSet__c WHERE Name = :sName];
                return false;
            } catch (Exception e) {
                List<Question__c> qList = [SELECT Id FROM Question__c WHERE Name IN :nameList];

                QuestionSet__c qSet = new QuestionSet__c();
                qSet.Name = sName;
                INSERT qSet;

                List<QuestionSetEntry__c> insertList = new List<QuestionSetEntry__c>();
                for (Question__c question : qList) {
                    QuestionSetEntry__c qSetEntry = new QuestionSetEntry__c();
                    qSetEntry.QuestionSet__c = qSet.Id;
                    qSetEntry.Question__c = question.Id;
                    insertList.add(qSetEntry);
                }

                INSERT insertList;

                return true;
            }
    }
}