CLIENT/CodeAssessMetadata/main/default/objects/Question__c/Question__c.object-meta.xml
<CustomObject>
    <label>Question</label>
    <nameField>
        <label>Question Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Questions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

CLIENT/CodeAssessMetadata/main/default/objects/Question__c/fields/QuestionTopic__c.field-meta.xml
<CustomField>
    <fullName>QuestionTopic__c</fullName>
    <label>QuestionTopic</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>QuestionTopics</valueSetName>
    </valueSet>
</CustomField>

CLIENT/CodeAssessMetadata/main/default/globalValueSets/QuestionTopics.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Apex Triggers</fullName>
    </customValue>
    <customValue>
        <fullName>Aura Components</fullName>
    </customValue>
    <customValue>
        <fullName>Events</fullName>
    </customValue>
    <customValue>
        <fullName>LWC</fullName>
    </customValue>
    <customValue>
        <fullName>SOQL</fullName>
    </customValue>
    <customValue>
        <fullName>SOSL</fullName>
    </customValue>
    <masterLabel>QuestionTopics</masterLabel>
</GlobalValueSet>

CLIENT/CodeAssess/main/default/classes/testQuestionCreatorControllerTest.cls
@isTest
public  class testQuestionCreatorControllerTest {
    @isTest
    public static void TP_topicPicklistVals (){
        Test.startTest();
        List<String> returnedVals = testQuestionCreatorController.topicPicklistValues(); 
        List<Schema.PicklistEntry> actualList = Question__c.QuestionTopic__c.getDescribe().getPicklistValues();

        Boolean missingEntry = false;
        for (Schema.PicklistEntry ple : actualList) {
            if (!returnedVals.contains(ple.getLabel())) {
                missingEntry = true;    
            }
        }
        System.assertEquals(false, missingEntry);
        Test.stopTest();
    }

    @isTest
    public static void TP_makeQuestion() {
        Blob testblob = Blob.valueOf('@isTest public class mockTest {}');
        String testClass = EncodingUtil.base64Encode(testBlob);
        ID created = testQuestionCreatorController.insertQuestion('mock question', 'SOQL', 'placeholder', 'dothis', testClass); 
        Question__c[] q = [SELECT id FROM Question__c WHERE id = :created];
        System.assertEquals(1, q.size());
    }
    
}