CANDIDATE/ApplicantEnvironment/rest/default/objects/ServerInfo__mdt/ServerInfo__mdt.object-meta.xml
<CustomObject>
    <label>ServerInfo</label>
    <pluralLabel>ServerInfos</pluralLabel>
</CustomObject>

CANDIDATE/ApplicantEnvironment/rest/default/objects/ServerInfo__mdt/fields/ServerUrl__c.field-meta.xml
<CustomField>
    <fullName>ServerUrl__c</fullName>
    <description>Link to Experience Site</description>
    <label>ServerUrl</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

CANDIDATE/ApplicantEnvironment/main/default/classes/AuthenticationController.cls
public without sharing class AuthenticationController {
    @AuraEnabled(cacheable=true)
    public static String SiteUrl() {
        ServerInfo__mdt server = [
            SELECT ServerUrl__c 
            FROM ServerInfo__mdt
            WHERE MasterLabel = 'Server' 
            LIMIT 1];
        return server.ServerUrl__c;
    }

    @AuraEnabled
    public static Boolean setSession(String code){
        AuthUtil.Authenticate(code);
        return true;
    }

    @AuraEnabled
    public static Boolean isAuthenticated(){
        return AuthUtil.isAuthenticated();
    }

    @AuraEnabled
    public static Boolean deAuthenticate(){
        AuthUtil.deauthenticate();
        return true;
    }
    @AuraEnabled
    public static Boolean expireToken(){
        AuthUtil.expireToken();
        return true;
    }
}