CLIENT/CodeAssessMetadata/main/default/objects/CandidateQuestionResult__c/CandidateQuestionResult__c.object-meta.xml
<CustomObject>
    <label>CandidateQuestionResult</label>
    <nameField>
        <displayFormat>Question Result {000000000}</displayFormat>
        <label>Question Result Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>CandidateQuestionResults</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

CLIENT/CodeAssessMetadata/main/default/objects/CandidateQuestionResult__c/fields/CandidateResult__c.field-meta.xml
<CustomField>
    <fullName>CandidateResult__c</fullName>
    <label>CandidateResult</label>
    <referenceTo>CandidateResult__c</referenceTo>
    <relationshipName>QuestionResults</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

CLIENT/CodeAssessMetadata/main/default/objects/CandidateQuestionResult__c/fields/MethodsPassed__c.field-meta.xml
<CustomField>
    <fullName>MethodsPassed__c</fullName>
    <label>Methods Passed</label>
    <summaryFilterItems>
        <field>CandidateMethodResult__c.Outcome__c</field>
        <operation>equals</operation>
        <value>Pass</value>
    </summaryFilterItems>
    <summaryForeignKey>CandidateMethodResult__c.CandidateQuestionResult__c</summaryForeignKey>
    <summaryOperation>count</summaryOperation>
    <type>Summary</type>
</CustomField>

CLIENT/CodeAssessMetadata/main/default/objects/CandidateQuestionResult__c/fields/Question__c.field-meta.xml
<CustomField>
    <fullName>Question__c</fullName>
    <label>Question</label>
    <referenceTo>Question__c</referenceTo>
    <relationshipName>QuestionResults</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

CLIENT/CodeAssessMetadata/main/default/objects/CandidateQuestionResult__c/fields/Result__c.field-meta.xml
<CustomField>
    <fullName>Result__c</fullName>
    <label>Result</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Result_Status</valueSetName>
    </valueSet>
</CustomField>

CLIENT/CodeAssessMetadata/main/default/objects/CandidateQuestionResult__c/fields/SubmitTime__c.field-meta.xml
<CustomField>
    <fullName>SubmitTime__c</fullName>
    <label>Submit Time</label>
    <type>DateTime</type>
</CustomField>

CLIENT/CodeAssessMetadata/main/default/objects/CandidateQuestionResult__c/fields/TotalMethods__c.field-meta.xml
<CustomField>
    <fullName>TotalMethods__c</fullName>
    <label>Total Methods</label>
    <summaryForeignKey>CandidateMethodResult__c.CandidateQuestionResult__c</summaryForeignKey>
    <summaryOperation>count</summaryOperation>
    <type>Summary</type>
</CustomField>

CLIENT/CodeAssessMetadata/main/default/objects/CandidateResult__c/CandidateResult__c.object-meta.xml
<CustomObject>
    <label>Candidate Result</label>
    <nameField>
        <displayFormat>Candidate Result {000000000}</displayFormat>
        <label>Candidate Result Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Candidate Results</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

CLIENT/CodeAssessMetadata/main/default/objects/CandidateResult__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Candidate Results</relationshipLabel>
    <relationshipName>Candidate_Results</relationshipName>
    <type>Lookup</type>
</CustomField>

CLIENT/CodeAssessMetadata/main/default/objects/CandidateResult__c/fields/StartTime__c.field-meta.xml
<CustomField>
    <fullName>StartTime__c</fullName>
    <label>Start Time</label>
    <type>DateTime</type>
</CustomField>

CLIENT/CodeAssessMetadata/main/default/objects/CandidateResult__c/fields/SubmitTime__c.field-meta.xml
<CustomField>
    <fullName>SubmitTime__c</fullName>
    <description>The time these candidate results were submitted by the candidate</description>
    <label>Submit Time</label>
    <type>DateTime</type>
</CustomField>

CLIENT/CodeAssessMetadata/main/default/objects/Question__c/Question__c.object-meta.xml
<CustomObject>
    <label>Question</label>
    <nameField>
        <label>Question Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Questions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

CLIENT/CodeAssessMetadata/main/default/objects/Question__c/fields/QuestionTopic__c.field-meta.xml
<CustomField>
    <fullName>QuestionTopic__c</fullName>
    <label>QuestionTopic</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>QuestionTopics</valueSetName>
    </valueSet>
</CustomField>

CLIENT/CodeAssessMetadata/main/default/globalValueSets/QuestionTopics.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Apex Triggers</fullName>
    </customValue>
    <customValue>
        <fullName>Aura Components</fullName>
    </customValue>
    <customValue>
        <fullName>Events</fullName>
    </customValue>
    <customValue>
        <fullName>LWC</fullName>
    </customValue>
    <customValue>
        <fullName>SOQL</fullName>
    </customValue>
    <customValue>
        <fullName>SOSL</fullName>
    </customValue>
    <masterLabel>QuestionTopics</masterLabel>
</GlobalValueSet>

CLIENT/CodeAssessMetadata/main/default/globalValueSets/Result_Status.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Pass</fullName>
    </customValue>
    <customValue>
        <fullName>Fail</fullName>
    </customValue>
    <customValue>
        <fullName>Compile Fail</fullName>
    </customValue>
    <customValue>
        <fullName>Skip</fullName>
    </customValue>
    <masterLabel>Result Status</masterLabel>
</GlobalValueSet>

CLIENT/CodeAssess/main/default/classes/candidateInformationController.cls
public without sharing class candidateInformationController {
    
    @AuraEnabled
    public static CandidateResult__c getCandidateInfo(id record) {
        return [SELECT Contact__r.Name, Contact__r.Email, Contact__r.Phone FROM  CandidateResult__c WHERE Id = :record LIMIT 1];
    }

    @AuraEnabled
    public static List<CandidateQuestionResult__c> getCandidateSummary(id record) {
        return [SELECT Result__c, MethodsPassed__c, TotalMethods__c, CandidateResult__r.id, CandidateResult__r.StartTime__c, CandidateResult__r.SubmitTime__c FROM CandidateQuestionResult__c WHERE CandidateResult__r.id = :record];
    }

    @AuraEnabled
    public static List<CandidateQuestionResult__c> getCandidateTestResults(id record) {
        return [SELECT Result__c, MethodsPassed__c, TotalMethods__c, Question__r.QuestionTopic__c, CandidateResult__r.id FROM CandidateQuestionResult__c WHERE CandidateResult__r.id = :record];
    }
}